const suits=['♠','♥','♦','♣'],ranks=['A','2','3','4','5','6','7','8','9','10','J','Q','K'];
const betNames={player:'闲',banker:'庄',tie:'和',playerPair:'闲对',bankerPair:'庄对',anyPair:'任意对子',perfectPair:'完美对子',big:'大',small:'小'};
const odds={player:1,banker:.95,tie:8,playerPair:11,bankerPair:11,anyPair:5,perfectPair:25,big:.54,small:1.5};
const bets=Object.fromEntries(Object.keys(betNames).map(k=>[k,0]));
const $=id=>document.getElementById(id);const el={money:$('money'),shoeNo:$('shoeNo'),roundNo:$('roundNo'),shoeLeft:$('shoeLeft'),pMini:$('pMini'),bMini:$('bMini'),message:$('message'),status:$('statusText'),count:$('countdown'),ring:$('timerRing'),total:$('totalBet'),bead:$('beadRoad'),big:$('bigRoad'),bWins:$('bWins'),pWins:$('pWins'),tWins:$('tWins'),winRate:$('winRate'),dealBtn:$('dealBtn'),repeatBtn:$('repeatBtn'),cancelBtn:$('cancelBtn'),resetBtn:$('resetBtn'),soundBtn:$('soundBtn')};
let money=+(localStorage.vip_final_money||100000),shoeNo=+(localStorage.vip_final_shoe||0),roundNo=+(localStorage.vip_final_round||0),shoe=[],chip=1000,history=JSON.parse(localStorage.vip_final_history||'[]'),betRecord=JSON.parse(localStorage.vip_final_record||'[]'),lastBets=JSON.parse(localStorage.vip_final_last||'{}'),timer=15,timerId=null,locked=false,betting=true,soundOn=localStorage.vip_final_sound!=='off';
function save(){localStorage.vip_final_money=money;localStorage.vip_final_shoe=shoeNo;localStorage.vip_final_round=roundNo;localStorage.vip_final_history=JSON.stringify(history);localStorage.vip_final_record=JSON.stringify(betRecord);localStorage.vip_final_last=JSON.stringify(lastBets);localStorage.vip_final_sound=soundOn?'on':'off'}
function fmt(n){return Math.round(n).toLocaleString('zh-CN')}function msg(t){el.message.innerHTML=t}function totalBet(){return Object.values(bets).reduce((a,b)=>a+b,0)}
function beep(f=600,d=.05){if(!soundOn)return;try{const c=new (window.AudioContext||window.webkitAudioContext)(),o=c.createOscillator(),g=c.createGain();o.frequency.value=f;g.gain.value=.035;o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+d);setTimeout(()=>c.close(),d*1000+40)}catch(e){}}
function initShoe(){shoe=[];for(let d=0;d<8;d++)for(const s of suits)for(const r of ranks)shoe.push({rank:r,suit:s});for(let i=shoe.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[shoe[i],shoe[j]]=[shoe[j],shoe[i]]}shoeNo++;roundNo=0}
function draw(){if(shoe.length<18)initShoe();return shoe.pop()}function val(c){if(c.rank==='A')return 1;if(['10','J','Q','K'].includes(c.rank))return 0;return +c.rank}function score(h){return h.reduce((s,c)=>s+val(c),0)%10}function sameRank(a,b){return a.rank===b.rank}function sameCard(a,b){return a.rank===b.rank&&a.suit===b.suit}
function bankerDraw(bs,pt){if(pt===null)return bs<=5;if(bs<=2)return true;if(bs===3)return pt!==8;if(bs===4)return pt>=2&&pt<=7;if(bs===5)return pt>=4&&pt<=7;if(bs===6)return pt===6||pt===7;return false}
function makeRound(){const p=[draw(),draw()],b=[draw(),draw()];let ps=score(p),bs=score(b),pt=null;if(ps<8&&bs<8){if(ps<=5){const c=draw();p.push(c);pt=val(c);bs=score(b);if(bankerDraw(bs,pt))b.push(draw())}else if(bs<=5)b.push(draw())}ps=score(p);bs=score(b);const winner=ps>bs?'player':bs>ps?'banker':'tie',total=p.length+b.length;return{p,b,ps,bs,winner,total,flags:{playerPair:sameRank(p[0],p[1]),bankerPair:sameRank(b[0],b[1]),anyPair:sameRank(p[0],p[1])||sameRank(b[0],b[1]),perfectPair:sameCard(p[0],p[1])||sameCard(b[0],b[1]),big:total>=5,small:total===4}}}
function card(c,back=false){const red=c&&(c.suit==='♥'||c.suit==='♦');return `<div class="card ${back?'back':''} ${red?'red':''}">${back?'':`<span>${c.rank}</span><small>${c.suit}</small>`}</div>`}
function clearTable(){el.pMini.innerHTML='';el.bMini.innerHTML='';document.querySelectorAll('.bet').forEach(x=>x.classList.remove('win'))}
function showBack(side){(side==='p'?el.pMini:el.bMini).insertAdjacentHTML('beforeend',card({},true));beep(side==='p'?520:580)}
function flipCard(side,i,c){const box=side==='p'?el.pMini:el.bMini,old=box.children[i];if(!old)return;old.className='card flip '+((c.suit==='♥'||c.suit==='♦')?'red':'');old.innerHTML=`<span>${c.rank}</span><small>${c.suit}</small>`;beep(720)}
function updateUI(){el.money.textContent=fmt(money);el.shoeNo.textContent=shoeNo;el.roundNo.textContent=roundNo;el.shoeLeft.textContent=shoe.length;el.total.textContent=fmt(totalBet());el.soundBtn.textContent=soundOn?'🔊':'🔇';for(const k in bets){const a=$('amount_'+k);if(a)a.textContent=bets[k]?fmt(bets[k]):'0'}document.querySelectorAll('.bet').forEach(x=>x.classList.toggle('betOn',(bets[x.dataset.bet]||0)>0));el.bWins.textContent=history.filter(x=>x==='banker').length;el.pWins.textContent=history.filter(x=>x==='player').length;el.tWins.textContent=history.filter(x=>x==='tie').length;const w=betRecord.filter(x=>x==='win').length,l=betRecord.filter(x=>x==='lose').length;el.winRate.textContent=w+l?Math.round(w/(w+l)*100)+'%':'0%';renderRoads();save()}
function placeBet(k){if(!betting||locked)return;if(money<chip){msg('余额不足');return}money-=chip;bets[k]+=chip;msg(`已下注 ${betNames[k]} ${fmt(chip)}`);flyChip(k);beep(690);updateUI()}
function flyChip(k){const t=document.querySelector(`[data-bet="${k}"]`);if(!t)return;const c=document.createElement('div');c.className='flyingChip';c.textContent=chip>=10000?chip/10000+'W':chip>=1000?chip/1000+'K':chip;document.body.appendChild(c);c.style.left='50%';c.style.bottom='130px';const r=t.getBoundingClientRect();requestAnimationFrame(()=>{c.style.left=r.left+r.width/2-16+'px';c.style.bottom=innerHeight-r.top-r.height/2-16+'px';c.style.opacity='.2';c.style.transform='scale(.6)'});setTimeout(()=>c.remove(),330)}
function clearBets(){if(!betting||locked)return;money+=totalBet();for(const k in bets)bets[k]=0;msg('已撤销本局下注');updateUI()}function repeatBet(){if(!betting||locked)return;const arr=Object.entries(lastBets).filter(x=>x[1]>0),need=arr.reduce((s,x)=>s+x[1],0);if(!arr.length)return msg('暂无上一局下注');if(money<need)return msg('余额不足，不能重复下注');arr.forEach(([k,v])=>{bets[k]+=v;money-=v});msg('已重复上一局下注');updateUI()}
function startDeal(){if(locked)return;if(totalBet()<=0){msg('请先下注'); timer=15; if(el.count)el.count.textContent=timer; if(el.ring)el.ring.style.setProperty('--p',100); return;}locked=true;betting=false;stopTimer();roundNo++;clearTable();el.status.textContent='发牌中';msg('停止下注，开始发牌');const r=makeRound();const seq=[['p',0,r.p[0]],['b',0,r.b[0]],['p',1,r.p[1]],['b',1,r.b[1]]];if(r.p[2])seq.push(['p',2,r.p[2]]);if(r.b[2])seq.push(['b',2,r.b[2]]);let d=0;seq.forEach(([s,i,c])=>{setTimeout(()=>showBack(s),d);setTimeout(()=>flipCard(s,i,c),d+620);d+=920});setTimeout(()=>settle(r),d+250)}
function settle(r){let payout=0,profit=-totalBet(),wins=[];if(r.winner==='player'&&bets.player){payout+=bets.player*2;wins.push('player')}if(r.winner==='banker'&&bets.banker){payout+=bets.banker*(1+odds.banker);wins.push('banker')}if(r.winner==='tie'){if(bets.tie){payout+=bets.tie*(1+odds.tie);wins.push('tie')}if(bets.player){payout+=bets.player;profit+=bets.player}if(bets.banker){payout+=bets.banker;profit+=bets.banker}}
['playerPair','bankerPair','anyPair','perfectPair','big','small'].forEach(k=>{if(r.flags[k]&&bets[k]){payout+=bets[k]*(1+odds[k]);wins.push(k)}});payout=Math.floor(payout);profit+=payout;money+=payout;wins.forEach(k=>document.querySelector(`[data-bet="${k}"]`)?.classList.add('win'));history.push(r.winner);if(history.length>120)history.shift();betRecord.push(profit>0?'win':profit<0?'lose':'push');if(betRecord.length>120)betRecord.shift();lastBets={...bets};const name=r.winner==='player'?'闲赢':r.winner==='banker'?'庄赢':'和局';el.status.textContent=`${name} ${r.ps}-${r.bs}`;msg(`${name}　闲 ${r.ps} / 庄 ${r.bs}　${profit>=0?'盈利 +'+fmt(profit):'亏损 '+fmt(profit)}`);for(const k in bets)bets[k]=0;beep(profit>=0?880:320,.08);updateUI();setTimeout(nextRound,3300)}
function nextRound(){locked=false;betting=true;timer=15;clearTable();el.status.textContent='等待下注';msg('请选择筹码下注');startTimer();updateUI()}
function startTimer(){stopTimer();el.count.textContent=timer;el.ring.style.setProperty('--p',100);timerId=setInterval(()=>{if(!betting||locked)return;timer--;el.count.textContent=timer;el.ring.style.setProperty('--p',timer/15*100);if(timer<=0)startDeal()},1000)}function stopTimer(){clearInterval(timerId);timerId=null}
function renderRoads(){el.bead.innerHTML=history.slice(-96).map(x=>`<div class="dot ${x}Dot">${x==='banker'?'庄':x==='player'?'闲':'和'}</div>`).join('');el.big.innerHTML=history.slice(-96).map(x=>`<div class="bigDot ${x}Dot"></div>`).join('')}
function resetAll(){money=100000;history=[];betRecord=[];lastBets={};for(const k in bets)bets[k]=0;shoeNo=0;initShoe();roundNo=0;timer=15;locked=false;betting=true;clearTable();msg('已重置模拟桌台');startTimer();updateUI()}
function fast(sel,fn){document.querySelectorAll(sel).forEach(n=>{let last=0;const run=e=>{const now=Date.now();if(e.type==='click'&&now-last<450)return;last=now;e.preventDefault();fn(n,e)};n.addEventListener('pointerdown',run,{passive:false});n.addEventListener('click',run,{passive:false});})}fast('.chip',n=>{chip=+n.dataset.chip;document.querySelectorAll('.chip').forEach(x=>x.classList.remove('active'));n.classList.add('active');beep(520)});fast('.bet',n=>placeBet(n.dataset.bet));el.dealBtn.addEventListener('pointerdown',e=>{e.preventDefault();startDeal()},{passive:false});el.cancelBtn.addEventListener('pointerdown',e=>{e.preventDefault();clearBets()},{passive:false});el.repeatBtn.addEventListener('pointerdown',e=>{e.preventDefault();repeatBet()},{passive:false});el.resetBtn.addEventListener('pointerdown',e=>{e.preventDefault();resetAll()},{passive:false});el.soundBtn.addEventListener('pointerdown',e=>{e.preventDefault();soundOn=!soundOn;updateUI();beep(760)},{passive:false});
if(!shoe.length)initShoe();updateUI();startTimer();
